### ISSUE TITLE
[HELP] Running error: 'EntryPoints' object has no attribute 'get' or SocketcanBus was not properly shut down 

### ISSUE THREAD

**Issue by lagoon-come-strep** [thingsboard/thingsboard-gateway#1739]
This issue is in same context than the following issue:
https://github.com/thingsboard/thingsboard-gateway/issues/1734
but I have upgraded to `scarthgap` and use exactly thingsboard-gateway v3.6.2 

**Describe the issue**

I am trying to install thingsboard-gateway 3.6.2 on an yocto image (build with Scarthgap) running on a raspberrypi 64 bits.
I have created all recipe dependencies, but I am a bit struggle with the error `AttributeError: 'EntryPoints' object has no attribute 'get'`.
This error seems to be with the **can** connector.

I found [here](https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean) that was due to the version of `importlib-metadata`. The version shall be strictly under 5.0.

But when I install this package, I have still an error. And it seems to work also without this package. I think I'm missing/missconfigured a package.

I'm using `python-can` version 4.1.0, that can also hold the error.
I get this error by downgrading `python-can` from version 4.2.2 to 4.1.0 to avoid `SocketcanBus was not properly shut down` error.
Indeed, my working configuration have  `python-can` version 4.1.0, but maybe it's better to fix the above error than the below one.

Here the error with `python-can` version 4.1.0 & `importlib-metadata` version 4.13.0 :
```
2025-01-08 18:24:43 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 187 - Gateway starting...
2025-01-08 18:24:43 - |WARNING| - [tb_updater.py] - tb_updater - check_for_new_version - 87 - Cannot connect to the update service. Please check your internet connection.
2025-01-08 18:24:43 - |WARNING| - [tb_updater.py] - tb_updater - check_for_new_version - 87 - Cannot connect to the update service. Please check your internet connection.
2025-01-08 18:24:43 - |INFO| - [tb_gateway_service.py] - tb_gateway_service - __init__ - 198 - ThingsBoard IoT gateway version: 3.6.2
2025-01-08 18:24:43 - |ERROR| - [tb_logger.py] - tb_logger - exception - 162 - 'EntryPoints' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/thingsboard_gateway/tb_utility/tb_loader.py", line 69, in import_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/thingsboard_gateway/connectors/can/can_connector.py", line 30, in <module>
    from can import Notifier, BufferedReader, Message, CanError, ThreadSafeBus
  File "/usr/lib/python3.12/site-packages/can/__init__.py", line 27, in <module>
    from .util import set_logging_level
  File "/usr/lib/python3.12/site-packages/can/util.py", line 18, in <module>
    from .interfaces import VALID_INTERFACES
  File "/usr/lib/python3.12/site-packages/can/interfaces/__init__.py", line 38, in <module>
    entries = entry_points().get("can.interface", ())
              ^^^^^^^^^^^^^^^^^^
AttributeError: 'EntryPoints' object has no attribute 'get'
```

And here the `pip3 freeze` command result on target:
```
aenum==3.1.15
attr==0.3.2
cachetools==5.3.3                                         // Thingsboard gateway dependency
certifi==2024.2.2
cffi==1.16.0
chardet==5.2.0
cryptography==42.0.5                                  // Thingsboard gateway dependency
decorator==5.1.1
grpcio==1.62.2                                               // Thingsboard gateway dependency
idna==3.7
importlib_metadata==4.13.0                      // To try to fix the error, but don't seems needed
jsonpath-rw==1.4.0                                      // Thingsboard gateway dependency
mmh3==4.0.1                                                // Thingsboard gateway dependency
more-itertools==10.2.0
orjson==3.9.9                                                 // Thingsboard gateway dependency
packaging==23.1                                          // Thingsboard gateway dependency     (!) version shall be equal to 23.1
pathlib2==2.3.7
ply==3.11
prompt_toolkit==3.0.43
protobuf==4.25.3                                          // Thingsboard gateway dependency   (!) No version constraint in requires.txt, but one in github
psutil==5.9.8                                                   // Thingsboard gateway dependency
pyasn1==0.5.1
pyasn1_modules==0.4.0
pybase64==1.4.1                                           // Thingsboard gateway dependency
pycparser==2.21
pyOpenSSL==24.0.0
pyrsistent==0.20.0                                       // Thingsboard gateway dependency
PySocks==1.7.1
python-can==4.1.0                                      // Our can conector dependency
PyYAML==6.0.1                                             // Thingsboard gateway dependency
questionary==2.1.0                                      // Thingsboard gateway dependency
regex==2024.4.16                                        // Thingsboard gateway dependency
requests==2.32.3                                         // Thingsboard gateway dependency     (!) version shall be >= 2.31.0
service-identity==21.1.0                              // Thingsboard gateway dependency
setuptools==69.1.1                                     // Thingsboard gateway dependency
simplejson==3.19.2                                     // Thingsboard gateway dependency
six==1.16.0
tb-mqtt-client==1.13.5                                 // Thingsboard gateway dependency
tb-paho-mqtt-client==2.1.2                        // tb-mqtt-client dependency, but get with paho-mqtt~=2.1.0 in github 
thingsboard-gateway==3.6.2
typing_extensions==4.10.0
urllib3==1.26.15                                           // Thingsboard gateway dependency   (!) version shall be <= 1.26.15
wcwidth==0.2.13
wrapt==1.16.0
zipp==3.17.0
```
"Thingsboard gateway dependency" are direct dependency for thingsboard gateway.

I found the list [here](https://github.com/thingsboard/thingsboard-gateway/blob/release/3.6.2/requirements.txt),
but it is different from the `requires.txt` of `thingsboard_gateway.egg-info` in `thingsboard_gateway-3.6.2` package (found in [PyPI](https://pypi.org/project/thingsboard-gateway/3.6.2/)). The above dependency are from the egg-info, I don't really know which one I shall follow.
Content is:
```
setuptools
cryptography
jsonpath-rw
regex
pip
PyYAML
orjson
pybase64
simplejson
urllib3<=1.26.15
requests>=2.31.0
questionary
pyfiglet
termcolor
mmh3
grpcio
protobuf
cachetools
tb-mqtt-client>=1.10.10
packaging==23.1
service-identity
psutil
```

**Connector name (If you need help with some connector/converter):**
CAN Connector

**Versions (please complete the following information):**
 - OS: poky Yocto (for Raspberry Pi 64 bits)
 - Thingsboard IoT Gateway version 3.6.2
 - Python 3.12.9

**Comment by lagoon-come-strep** [comment]
The `'EntryPoints' object has no attribute 'get'` error was due to the usage of a python version with new interface of `importlib-metadata`. As the module is Python content, it will import his internal package instead of installed one, upgrade to 3.7.3 fix this problem.

After upgrading to 3.7.3, I get back to a previous error: `Error on CAN bus: [Errno 97] Address family not supported by protocol` .

kernel was not configured properly and was missing following configuration to be able to use socket can (with [raspberry pi kernel v6.6.y](https://github.com/raspberrypi/linux/blob/rpi-6.6.y/arch/arm64/configs/bcmrpi3_defconfig):
```
CONFIG_CAN=y
CONFIG_CAN_RAW=y
CONFIG_CAN_DEV=y
```
